import React, { useState, useMemo } from 'react';
import { 
  Search, 
  X, 
  ExternalLink, 
  Package, 
  ShoppingCart, 
  Tag, 
  TrendingUp, 
  Clock, 
  Smartphone, 
  Laptop, 
  MapPin, 
  Calendar, 
  ArrowRight, 
  Copy, 
  Check, 
  Sparkles, 
  Eye, 
  Flame, 
  Filter, 
  Layers, 
  Globe, 
  ChevronRight, 
  ShoppingBag, 
  BarChart3,
  User,
  ShieldCheck,
  AlertCircle
} from 'lucide-react';
import { Product, VisitorLog } from '../types';

interface SearchQueryHistoryModalProps {
  isOpen: boolean;
  onClose: () => void;
  query: string;
  rank?: number;
  totalSearchCount?: number;
  logs: VisitorLog[];
  products: Product[];
  isDark?: boolean;
  onNavigateToClient?: (query: string) => void;
  onNavigateToInventory?: (query: string) => void;
  onNavigateToOffers?: (query: string) => void;
  onFilterInteractionLogs?: (query: string) => void;
  onInspectVisitorJourney?: (visitorId: string) => void;
  onSelectProduct?: (productId: string) => void;
}

export const SearchQueryHistoryModal: React.FC<SearchQueryHistoryModalProps> = ({
  isOpen,
  onClose,
  query,
  rank,
  totalSearchCount,
  logs = [],
  products = [],
  isDark = false,
  onNavigateToClient,
  onNavigateToInventory,
  onNavigateToOffers,
  onFilterInteractionLogs,
  onInspectVisitorJourney,
  onSelectProduct,
}) => {
  const [activeSubTab, setActiveSubTab] = useState<'timeline' | 'products' | 'insights'>('timeline');
  const [copied, setCopied] = useState(false);
  const [copiedVisitorId, setCopiedVisitorId] = useState<string | null>(null);

  if (!isOpen || !query) return null;

  const normalizedQuery = query.trim().toLowerCase();

  // All logs directly representing this search query
  const querySearchLogs = useMemo(() => {
    return logs.filter(l => 
      l.interactionType === 'SEARCH' && 
      (l.searchQuery?.trim().toLowerCase() === normalizedQuery || l.searchQuery?.trim().toLowerCase().includes(normalizedQuery))
    ).sort((a, b) => new Date(b.createdAt).getTime() - new Date(a.createdAt).getTime());
  }, [logs, normalizedQuery]);

  // Unique visitors who searched this query
  const uniqueVisitorIds = useMemo(() => {
    return Array.from(new Set(querySearchLogs.map(l => l.visitorId)));
  }, [querySearchLogs]);

  // All logs generated by these visitors to measure downstream conversion (Product Views, Add to Cart, Orders)
  const downstreamVisitorLogs = useMemo(() => {
    if (uniqueVisitorIds.length === 0) return [];
    const visitorSet = new Set(uniqueVisitorIds);
    return logs.filter(l => visitorSet.has(l.visitorId));
  }, [logs, uniqueVisitorIds]);

  // Products viewed/added after searching
  const downstreamProductConversions = useMemo(() => {
    const productStatsMap = new Map<string, { product?: Product; views: number; cartAdds: number; orders: number; name: string; category: string }>();

    downstreamVisitorLogs.forEach(l => {
      if (l.productId) {
        const existing = productStatsMap.get(l.productId) || {
          product: products.find(p => p.id === l.productId),
          views: 0,
          cartAdds: 0,
          orders: 0,
          name: l.productName || 'Unknown Product',
          category: l.productCategory || 'Electronics'
        };

        if (l.interactionType === 'PRODUCT_VIEW') existing.views += 1;
        if (l.interactionType === 'ADD_TO_CART' || l.interactionType === 'EXPRESS_BUY_OPEN') existing.cartAdds += 1;
        if (l.interactionType === 'ORDER_PLACED') existing.orders += 1;

        productStatsMap.set(l.productId, existing);
      }
    });

    // Also include products matching query keyword if not already in map
    products.forEach(p => {
      const matchName = p.name.toLowerCase().includes(normalizedQuery);
      const matchCategory = p.category.toLowerCase().includes(normalizedQuery);
      const matchDesc = p.description?.toLowerCase().includes(normalizedQuery);
      if ((matchName || matchCategory || matchDesc) && !productStatsMap.has(p.id)) {
        productStatsMap.set(p.id, {
          product: p,
          views: 0,
          cartAdds: 0,
          orders: 0,
          name: p.name,
          category: p.category
        });
      }
    });

    return Array.from(productStatsMap.values()).sort((a, b) => (b.views + b.cartAdds * 2) - (a.views + a.cartAdds * 2));
  }, [downstreamVisitorLogs, products, normalizedQuery]);

  // Correlated other searches performed in same visitor sessions
  const correlatedQueries = useMemo(() => {
    const counts: Record<string, number> = {};
    downstreamVisitorLogs.forEach(l => {
      if (l.interactionType === 'SEARCH' && l.searchQuery) {
        const q = l.searchQuery.trim();
        if (q.toLowerCase() !== normalizedQuery) {
          counts[q] = (counts[q] || 0) + 1;
        }
      }
    });
    return Object.entries(counts)
      .map(([q, count]) => ({ query: q, count }))
      .sort((a, b) => b.count - a.count)
      .slice(0, 6);
  }, [downstreamVisitorLogs, normalizedQuery]);

  // Device Breakdown for this query
  const deviceCounts = useMemo(() => {
    let mobile = 0;
    let desktop = 0;
    let tablet = 0;
    querySearchLogs.forEach(l => {
      if (l.deviceType === 'Mobile') mobile++;
      else if (l.deviceType === 'Desktop') desktop++;
      else if (l.deviceType === 'Tablet') tablet++;
      else mobile++; // default
    });
    const total = Math.max(querySearchLogs.length, 1);
    return {
      mobile,
      desktop,
      tablet,
      mobilePct: Math.round((mobile / total) * 100),
      desktopPct: Math.round((desktop / total) * 100),
      tabletPct: Math.round((tablet / total) * 100)
    };
  }, [querySearchLogs]);

  // Overall effective count
  const effectiveCount = totalSearchCount || querySearchLogs.length;
  const totalProductViews = downstreamVisitorLogs.filter(l => l.interactionType === 'PRODUCT_VIEW').length;
  const totalCartAdds = downstreamVisitorLogs.filter(l => l.interactionType === 'ADD_TO_CART' || l.interactionType === 'EXPRESS_BUY_OPEN').length;
  const totalOrders = downstreamVisitorLogs.filter(l => l.interactionType === 'ORDER_PLACED').length;

  const conversionRate = effectiveCount > 0 
    ? Math.min(100, Math.round(((totalProductViews + totalCartAdds) / effectiveCount) * 100))
    : 0;

  const handleCopyQuery = () => {
    navigator.clipboard?.writeText(query);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handleCopyVisitor = (id: string, e: React.MouseEvent) => {
    e.stopPropagation();
    navigator.clipboard?.writeText(id);
    setCopiedVisitorId(id);
    setTimeout(() => setCopiedVisitorId(null), 2000);
  };

  // Helper formatting timestamp
  const formatTime = (iso: string) => {
    try {
      const d = new Date(iso);
      return d.toLocaleString('en-GB', {
        timeZone: 'Africa/Nairobi',
        day: '2-digit',
        month: 'short',
        hour: '2-digit',
        minute: '2-digit',
        second: '2-digit',
        hour12: false
      }) + ' EAT';
    } catch {
      return iso;
    }
  };

  return (
    <div className="fixed inset-0 z-50 bg-slate-950/80 backdrop-blur-sm flex items-center justify-center p-3 sm:p-4 overflow-y-auto animate-fadeIn">
      <div className={`w-full max-w-4xl rounded-3xl border shadow-2xl overflow-hidden my-auto flex flex-col max-h-[92vh] ${
        isDark ? 'bg-slate-900 border-slate-800 text-white' : 'bg-white border-slate-200 text-slate-900'
      }`}>
        {/* Modal Top Header */}
        <div className={`p-5 sm:p-6 border-b flex items-start justify-between gap-4 ${
          isDark ? 'border-slate-800 bg-slate-950/50' : 'border-slate-100 bg-slate-50/80'
        }`}>
          <div className="space-y-2 min-w-0">
            <div className="flex items-center gap-2 flex-wrap">
              <span className={`inline-flex items-center gap-1.5 px-3 py-1 rounded-full text-xs font-black uppercase tracking-wider border ${
                isDark ? 'bg-amber-950/60 text-amber-300 border-amber-800/60' : 'bg-amber-50 text-amber-700 border-amber-200'
              }`}>
                <Search className="w-3.5 h-3.5 text-amber-500" />
                <span>Search Intelligence</span>
                {rank && <span className="ml-1 text-[10px] px-1.5 py-0.2 rounded-md bg-amber-500 text-slate-950 font-black">#{rank}</span>}
              </span>

              <span className={`text-xs px-2.5 py-1 rounded-full border font-bold ${
                isDark ? 'bg-slate-800 border-slate-700 text-slate-300' : 'bg-white border-slate-200 text-slate-700'
              }`}>
                {effectiveCount} total queries recorded
              </span>
            </div>

            <div className="flex items-center gap-3">
              <h2 className="text-xl sm:text-2xl font-black tracking-tight text-blue-500 dark:text-blue-400 break-all">
                "{query}"
              </h2>
              <button
                type="button"
                onClick={handleCopyQuery}
                className={`p-1.5 rounded-lg border text-xs font-semibold transition-all ${
                  isDark ? 'bg-slate-800 border-slate-700 hover:bg-slate-700 text-slate-300' : 'bg-white border-slate-200 hover:bg-slate-100 text-slate-700'
                }`}
                title="Copy query text"
              >
                {copied ? <Check className="w-3.5 h-3.5 text-emerald-400" /> : <Copy className="w-3.5 h-3.5" />}
              </button>
            </div>

            <p className={`text-xs ${isDark ? 'text-slate-400' : 'text-slate-500'}`}>
              Real-time audit of customer search intent, linked product views, conversion metrics, and multi-app navigation routes.
            </p>
          </div>

          <button
            type="button"
            onClick={onClose}
            className={`p-2 rounded-2xl border transition-all cursor-pointer shrink-0 ${
              isDark 
                ? 'bg-slate-800 border-slate-700 hover:bg-slate-700 text-slate-400 hover:text-white' 
                : 'bg-slate-100 border-slate-200 hover:bg-slate-200 text-slate-500 hover:text-slate-900'
            }`}
          >
            <X className="w-5 h-5" />
          </button>
        </div>

        {/* Real Analytics Navigation Action Bar */}
        <div className={`px-5 sm:px-6 py-3 border-b flex flex-wrap items-center justify-between gap-2.5 ${
          isDark ? 'bg-slate-950/80 border-slate-800' : 'bg-blue-50/50 border-blue-100'
        }`}>
          <div className="flex items-center gap-1.5 text-xs font-bold">
            <Sparkles className="w-4 h-4 text-amber-500 shrink-0" />
            <span className={isDark ? 'text-slate-200' : 'text-slate-800'}>Direct Action &amp; Routing:</span>
          </div>

          <div className="flex flex-wrap items-center gap-2">
            {/* 1. Jump to Client Storefront with this search */}
            {onNavigateToClient && (
              <button
                type="button"
                onClick={() => {
                  onNavigateToClient(query);
                  onClose();
                }}
                className="inline-flex items-center gap-1.5 px-3 py-1.5 rounded-xl bg-blue-600 hover:bg-blue-500 text-white text-xs font-bold shadow-sm transition-all cursor-pointer active:scale-95"
                title="Open Client Storefront and run this search live"
              >
                <Globe className="w-3.5 h-3.5" />
                <span>Search in Client Store</span>
                <ExternalLink className="w-3 h-3 opacity-70" />
              </button>
            )}

            {/* 2. Jump to Admin Inventory Catalog */}
            {onNavigateToInventory && (
              <button
                type="button"
                onClick={() => {
                  onNavigateToInventory(query);
                  onClose();
                }}
                className={`inline-flex items-center gap-1.5 px-3 py-1.5 rounded-xl border text-xs font-bold transition-all cursor-pointer ${
                  isDark 
                    ? 'bg-slate-800 hover:bg-slate-700 border-slate-700 text-slate-200' 
                    : 'bg-white hover:bg-slate-100 border-slate-200 text-slate-800'
                }`}
                title="Search and adjust stock in Admin Inventory"
              >
                <Package className="w-3.5 h-3.5 text-indigo-400" />
                <span>Find in Inventory Catalog</span>
              </button>
            )}

            {/* 3. Create Offer / Promo Deal */}
            {onNavigateToOffers && (
              <button
                type="button"
                onClick={() => {
                  onNavigateToOffers(query);
                  onClose();
                }}
                className={`inline-flex items-center gap-1.5 px-3 py-1.5 rounded-xl border text-xs font-bold transition-all cursor-pointer ${
                  isDark 
                    ? 'bg-amber-950/40 hover:bg-amber-900/50 border-amber-800/60 text-amber-300' 
                    : 'bg-amber-50 hover:bg-amber-100 border-amber-200 text-amber-800'
                }`}
                title="Launch promotional offer or discount for this keyword"
              >
                <Tag className="w-3.5 h-3.5 text-amber-500" />
                <span>Create Offer for Query</span>
              </button>
            )}

            {/* 4. Filter Full Logs Table */}
            {onFilterInteractionLogs && (
              <button
                type="button"
                onClick={() => {
                  onFilterInteractionLogs(query);
                  onClose();
                }}
                className={`inline-flex items-center gap-1.5 px-3 py-1.5 rounded-xl border text-xs font-bold transition-all cursor-pointer ${
                  isDark 
                    ? 'bg-slate-800/80 hover:bg-slate-700 border-slate-700 text-slate-300' 
                    : 'bg-slate-100 hover:bg-slate-200 border-slate-200 text-slate-700'
                }`}
                title="Lock filter onto the Interaction Logs table below"
              >
                <Filter className="w-3.5 h-3.5" />
                <span>Filter Table Logs</span>
              </button>
            )}
          </div>
        </div>

        {/* Demand Metrics Ribbon */}
        <div className={`grid grid-cols-2 sm:grid-cols-4 gap-3 p-5 sm:px-6 border-b ${
          isDark ? 'border-slate-800 bg-slate-900/50' : 'border-slate-100 bg-white'
        }`}>
          <div className={`p-3 rounded-2xl border ${isDark ? 'bg-slate-800/40 border-slate-700/50' : 'bg-slate-50 border-slate-100'}`}>
            <span className={`text-[11px] font-semibold ${isDark ? 'text-slate-400' : 'text-slate-500'}`}>Search Inquiries</span>
            <p className="text-xl font-black text-blue-500 dark:text-blue-400 mt-0.5">{effectiveCount}</p>
            <p className="text-[10px] text-slate-400 mt-0.5">{uniqueVisitorIds.length} unique buyers</p>
          </div>

          <div className={`p-3 rounded-2xl border ${isDark ? 'bg-slate-800/40 border-slate-700/50' : 'bg-slate-50 border-slate-100'}`}>
            <span className={`text-[11px] font-semibold ${isDark ? 'text-slate-400' : 'text-slate-500'}`}>Assisted Views</span>
            <p className="text-xl font-black text-emerald-500 dark:text-emerald-400 mt-0.5">{totalProductViews}</p>
            <p className="text-[10px] text-slate-400 mt-0.5">catalog clicks</p>
          </div>

          <div className={`p-3 rounded-2xl border ${isDark ? 'bg-slate-800/40 border-slate-700/50' : 'bg-slate-50 border-slate-100'}`}>
            <span className={`text-[11px] font-semibold ${isDark ? 'text-slate-400' : 'text-slate-500'}`}>Cart Additions</span>
            <p className="text-xl font-black text-purple-500 dark:text-purple-400 mt-0.5">{totalCartAdds}</p>
            <p className="text-[10px] text-slate-400 mt-0.5">{totalOrders > 0 ? `${totalOrders} orders completed` : 'buyer interest'}</p>
          </div>

          <div className={`p-3 rounded-2xl border ${isDark ? 'bg-slate-800/40 border-slate-700/50' : 'bg-slate-50 border-slate-100'}`}>
            <span className={`text-[11px] font-semibold ${isDark ? 'text-slate-400' : 'text-slate-500'}`}>Search Intent Score</span>
            <p className="text-xl font-black text-amber-500 dark:text-amber-400 mt-0.5">{conversionRate}%</p>
            <p className="text-[10px] text-slate-400 mt-0.5">view &amp; cart conversion</p>
          </div>
        </div>

        {/* Modal Navigation Sub-Tabs */}
        <div className={`px-5 sm:px-6 pt-3 border-b flex items-center gap-3 text-xs font-bold ${
          isDark ? 'border-slate-800 bg-slate-950/30' : 'border-slate-100 bg-slate-50/50'
        }`}>
          <button
            type="button"
            onClick={() => setActiveSubTab('timeline')}
            className={`pb-3 px-2 border-b-2 transition-all flex items-center gap-1.5 cursor-pointer ${
              activeSubTab === 'timeline'
                ? 'border-blue-500 text-blue-500 dark:text-blue-400'
                : 'border-transparent text-slate-400 hover:text-slate-700 dark:hover:text-slate-200'
            }`}
          >
            <Clock className="w-3.5 h-3.5" />
            <span>Search Events History ({querySearchLogs.length})</span>
          </button>

          <button
            type="button"
            onClick={() => setActiveSubTab('products')}
            className={`pb-3 px-2 border-b-2 transition-all flex items-center gap-1.5 cursor-pointer ${
              activeSubTab === 'products'
                ? 'border-blue-500 text-blue-500 dark:text-blue-400'
                : 'border-transparent text-slate-400 hover:text-slate-700 dark:hover:text-slate-200'
            }`}
          >
            <Package className="w-3.5 h-3.5" />
            <span>Matching &amp; Converted Products ({downstreamProductConversions.length})</span>
          </button>

          <button
            type="button"
            onClick={() => setActiveSubTab('insights')}
            className={`pb-3 px-2 border-b-2 transition-all flex items-center gap-1.5 cursor-pointer ${
              activeSubTab === 'insights'
                ? 'border-blue-500 text-blue-500 dark:text-blue-400'
                : 'border-transparent text-slate-400 hover:text-slate-700 dark:hover:text-slate-200'
            }`}
          >
            <BarChart3 className="w-3.5 h-3.5" />
            <span>Buyer Intent &amp; Devices</span>
          </button>
        </div>

        {/* Tab Body Content */}
        <div className="p-5 sm:p-6 overflow-y-auto flex-1 space-y-4">
          {/* TAB 1: SEARCH EVENTS TIMELINE */}
          {activeSubTab === 'timeline' && (
            <div className="space-y-3">
              <div className="flex items-center justify-between text-xs text-slate-500 dark:text-slate-400">
                <span>Detailed audit trail of each customer query event in chronological order:</span>
                <span className="font-mono text-[11px]">{querySearchLogs.length} events</span>
              </div>

              {querySearchLogs.length > 0 ? (
                <div className="space-y-2.5 max-h-[420px] overflow-y-auto pr-1">
                  {querySearchLogs.map((log, idx) => (
                    <div
                      key={log.id || idx}
                      className={`p-3.5 rounded-2xl border transition-all flex flex-col sm:flex-row sm:items-center justify-between gap-3 ${
                        isDark ? 'bg-slate-800/50 border-slate-700/60 hover:bg-slate-800' : 'bg-slate-50/90 border-slate-200/80 hover:bg-white'
                      }`}
                    >
                      <div className="space-y-1.5 min-w-0 flex-1">
                        <div className="flex items-center gap-2 flex-wrap">
                          <span className={`inline-flex items-center gap-1 px-2 py-0.5 rounded-md text-[11px] font-bold ${
                            isDark ? 'bg-amber-950/60 text-amber-300 border border-amber-800/60' : 'bg-amber-50 text-amber-700 border border-amber-200'
                          }`}>
                            <Search className="w-3 h-3 text-amber-500" />
                            Search Keyword: "{log.searchQuery}"
                          </span>

                          <span className={`text-[10px] px-2 py-0.5 rounded font-mono font-semibold ${
                            isDark ? 'bg-slate-900 text-slate-400' : 'bg-white text-slate-500 border border-slate-200'
                          }`}>
                            {log.searchResultsCount !== undefined ? `${log.searchResultsCount} results found` : '100% matched'}
                          </span>

                          {log.deviceType && (
                            <span className={`inline-flex items-center gap-1 text-[10px] px-1.5 py-0.5 rounded border ${
                              isDark ? 'bg-slate-900 border-slate-700 text-slate-400' : 'bg-white border-slate-200 text-slate-600'
                            }`}>
                              {log.deviceType === 'Mobile' ? <Smartphone className="w-2.5 h-2.5" /> : <Laptop className="w-2.5 h-2.5" />}
                              {log.deviceType}
                            </span>
                          )}
                        </div>

                        <div className="flex items-center gap-3 text-[11px] text-slate-400 flex-wrap">
                          <span className="flex items-center gap-1 text-slate-600 dark:text-slate-300 font-medium">
                            <Clock className="w-3 h-3 text-blue-400" />
                            {formatTime(log.createdAt)}
                          </span>

                          {log.city && (
                            <span className="flex items-center gap-1">
                              <MapPin className="w-3 h-3 text-slate-400" />
                              {log.city}, {log.country || 'Tanzania'}
                            </span>
                          )}

                          <div className="flex items-center gap-1">
                            <User className="w-3 h-3 text-slate-400" />
                            <span className="font-mono text-[10px]">ID: {log.visitorId.slice(0, 16)}...</span>
                            <button
                              type="button"
                              onClick={(e) => handleCopyVisitor(log.visitorId, e)}
                              className="text-slate-400 hover:text-blue-400 p-0.5"
                              title="Copy Visitor ID"
                            >
                              {copiedVisitorId === log.visitorId ? <Check className="w-3 h-3 text-emerald-400" /> : <Copy className="w-3 h-3" />}
                            </button>
                          </div>
                        </div>
                      </div>

                      {/* Right Action */}
                      <div className="flex items-center gap-2 shrink-0">
                        {onInspectVisitorJourney && (
                          <button
                            type="button"
                            onClick={() => {
                              onInspectVisitorJourney(log.visitorId);
                              onClose();
                            }}
                            className={`px-3 py-1.5 rounded-xl border text-xs font-bold flex items-center gap-1.5 transition-all cursor-pointer ${
                              isDark 
                                ? 'bg-slate-900 hover:bg-slate-700 border-slate-700 text-blue-400 hover:text-white' 
                                : 'bg-white hover:bg-blue-50 border-slate-200 text-blue-600 hover:border-blue-300 shadow-xs'
                            }`}
                            title="Inspect full timeline journey for this visitor"
                          >
                            <span>Inspect Session Journey</span>
                            <ChevronRight className="w-3.5 h-3.5" />
                          </button>
                        )}
                      </div>
                    </div>
                  ))}
                </div>
              ) : (
                <div className={`p-8 text-center rounded-2xl border ${isDark ? 'bg-slate-900 border-slate-800 text-slate-500' : 'bg-slate-50 border-slate-200 text-slate-400'}`}>
                  No specific individual search event logs found for this exact string in current window.
                </div>
              )}
            </div>
          )}

          {/* TAB 2: MATCHING & CONVERTED PRODUCTS */}
          {activeSubTab === 'products' && (
            <div className="space-y-3">
              <div className="flex items-center justify-between text-xs text-slate-500 dark:text-slate-400">
                <span>Products discovered, clicked, or correlated with "{query}":</span>
                <span>{downstreamProductConversions.length} inventory items</span>
              </div>

              {downstreamProductConversions.length > 0 ? (
                <div className="grid grid-cols-1 sm:grid-cols-2 gap-3 max-h-[420px] overflow-y-auto pr-1">
                  {downstreamProductConversions.map((item, idx) => {
                    const prod = item.product;
                    const stock = prod ? Number(prod.stock || 0) : 0;

                    return (
                      <div
                        key={idx}
                        className={`p-3.5 rounded-2xl border transition-all flex flex-col justify-between gap-3 ${
                          isDark ? 'bg-slate-800/60 border-slate-700/60 hover:border-blue-500/50' : 'bg-slate-50 border-slate-200 hover:border-blue-300'
                        }`}
                      >
                        <div className="flex items-start gap-3 min-w-0">
                          {prod?.image ? (
                            <img 
                              src={prod.image} 
                              alt={item.name} 
                              className="w-12 h-12 rounded-xl object-contain bg-white border border-slate-200 dark:border-slate-700 p-0.5 shrink-0"
                              referrerPolicy="no-referrer"
                            />
                          ) : (
                            <div className="w-12 h-12 rounded-xl bg-slate-200 dark:bg-slate-800 flex items-center justify-center text-slate-400 shrink-0">
                              <Package className="w-5 h-5" />
                            </div>
                          )}

                          <div className="min-w-0 flex-1">
                            <h4 className="text-xs font-bold truncate hover:text-blue-500" title={item.name}>
                              {item.name}
                            </h4>
                            <p className="text-[11px] text-slate-400 mt-0.5">{item.category}</p>
                            {prod?.price && (
                              <p className="text-xs font-extrabold text-blue-500 dark:text-blue-400 mt-1">
                                TZS {Number(prod.price).toLocaleString()}
                              </p>
                            )}
                          </div>
                        </div>

                        {/* Stock & Interaction Stats */}
                        <div className="flex items-center justify-between pt-2 border-t border-slate-200/50 dark:border-slate-700/50 text-[11px]">
                          <div className="flex items-center gap-1.5">
                            <span className={`px-2 py-0.5 rounded-md font-bold text-[10px] ${
                              stock > 5 
                                ? 'bg-emerald-100 dark:bg-emerald-950/60 text-emerald-700 dark:text-emerald-300' 
                                : stock > 0 
                                ? 'bg-amber-100 dark:bg-amber-950/60 text-amber-700 dark:text-amber-300'
                                : 'bg-rose-100 dark:bg-rose-950/60 text-rose-700 dark:text-rose-300'
                            }`}>
                              {stock > 0 ? `${stock} in stock` : 'Out of Stock'}
                            </span>
                            {item.views > 0 && (
                              <span className="text-slate-400 font-semibold">{item.views} views</span>
                            )}
                          </div>

                          <div className="flex items-center gap-1.5">
                            {onSelectProduct && prod && (
                              <button
                                type="button"
                                onClick={() => {
                                  onSelectProduct(prod.id);
                                  onClose();
                                }}
                                className="px-2 py-1 rounded-lg bg-blue-600/10 hover:bg-blue-600/20 text-blue-600 dark:text-blue-400 font-bold text-[11px] transition-colors cursor-pointer"
                                title="Filter visitor analytics to this product"
                              >
                                Filter Logs
                              </button>
                            )}
                            {onNavigateToInventory && prod && (
                              <button
                                type="button"
                                onClick={() => {
                                  onNavigateToInventory(prod.name);
                                  onClose();
                                }}
                                className={`p-1.5 rounded-lg border text-slate-400 hover:text-white transition-colors ${
                                  isDark ? 'border-slate-700 bg-slate-900' : 'border-slate-200 bg-white'
                                }`}
                                title="Edit in Inventory"
                              >
                                <Package className="w-3.5 h-3.5" />
                              </button>
                            )}
                          </div>
                        </div>
                      </div>
                    );
                  })}
                </div>
              ) : (
                <div className={`p-8 text-center rounded-2xl border ${isDark ? 'bg-slate-900 border-slate-800 text-slate-500' : 'bg-slate-50 border-slate-200 text-slate-400'}`}>
                  No matching inventory products found for this search string. Consider adding matching items to your catalog!
                </div>
              )}
            </div>
          )}

          {/* TAB 3: BUYER INTENT & DEVICES */}
          {activeSubTab === 'insights' && (
            <div className="space-y-4">
              <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
                {/* Device Breakdown */}
                <div className={`p-4 rounded-2xl border ${isDark ? 'bg-slate-800/40 border-slate-700/60' : 'bg-slate-50 border-slate-200'}`}>
                  <h4 className="text-xs font-bold mb-3 flex items-center gap-1.5">
                    <Smartphone className="w-4 h-4 text-blue-500" />
                    Device Distribution for "{query}"
                  </h4>
                  <div className="space-y-2.5 text-xs">
                    <div>
                      <div className="flex justify-between mb-1">
                        <span className="text-slate-400 flex items-center gap-1">
                          <Smartphone className="w-3 h-3" /> Mobile Smartphones
                        </span>
                        <span className="font-bold">{deviceCounts.mobile} ({deviceCounts.mobilePct}%)</span>
                      </div>
                      <div className={`h-2 rounded-full overflow-hidden ${isDark ? 'bg-slate-900' : 'bg-slate-200'}`}>
                        <div className="h-full bg-blue-500 rounded-full" style={{ width: `${deviceCounts.mobilePct}%` }} />
                      </div>
                    </div>

                    <div>
                      <div className="flex justify-between mb-1">
                        <span className="text-slate-400 flex items-center gap-1">
                          <Laptop className="w-3 h-3" /> Desktop Workstations
                        </span>
                        <span className="font-bold">{deviceCounts.desktop} ({deviceCounts.desktopPct}%)</span>
                      </div>
                      <div className={`h-2 rounded-full overflow-hidden ${isDark ? 'bg-slate-900' : 'bg-slate-200'}`}>
                        <div className="h-full bg-indigo-500 rounded-full" style={{ width: `${deviceCounts.desktopPct}%` }} />
                      </div>
                    </div>
                  </div>
                </div>

                {/* Related Keywords Searched in Same Sessions */}
                <div className={`p-4 rounded-2xl border ${isDark ? 'bg-slate-800/40 border-slate-700/60' : 'bg-slate-50 border-slate-200'}`}>
                  <h4 className="text-xs font-bold mb-3 flex items-center gap-1.5">
                    <Tag className="w-4 h-4 text-amber-500" />
                    Correlated Searches in Same Visitor Sessions
                  </h4>
                  {correlatedQueries.length > 0 ? (
                    <div className="flex flex-wrap gap-1.5">
                      {correlatedQueries.map((cq, cqIdx) => (
                        <button
                          key={cqIdx}
                          type="button"
                          onClick={() => {
                            if (onFilterInteractionLogs) onFilterInteractionLogs(cq.query);
                            onClose();
                          }}
                          className={`inline-flex items-center gap-1.5 px-2.5 py-1 rounded-xl text-xs font-semibold border transition-all cursor-pointer ${
                            isDark 
                              ? 'bg-slate-900 border-slate-700 hover:border-amber-500/60 text-slate-300' 
                              : 'bg-white border-slate-200 hover:border-amber-400 text-slate-700 shadow-xs'
                          }`}
                          title={`Search logs for ${cq.query}`}
                        >
                          <Search className="w-3 h-3 text-amber-500" />
                          <span>"{cq.query}"</span>
                          <span className="text-[10px] px-1 py-0.2 rounded bg-amber-500/20 text-amber-400 font-bold">
                            {cq.count}x
                          </span>
                        </button>
                      ))}
                    </div>
                  ) : (
                    <p className="text-xs text-slate-400">No secondary search queries recorded in these sessions yet.</p>
                  )}
                </div>
              </div>

              {/* Strategic Merchandising Recommendations */}
              <div className={`p-4 rounded-2xl border flex items-start gap-3 ${
                isDark ? 'bg-blue-950/30 border-blue-800/50 text-blue-200' : 'bg-blue-50 border-blue-200 text-blue-900'
              }`}>
                <Sparkles className="w-5 h-5 text-blue-500 shrink-0 mt-0.5" />
                <div className="space-y-1 text-xs leading-relaxed">
                  <h4 className="font-bold text-sm">Merchandising &amp; Catalog Strategy</h4>
                  <p>
                    <strong>"{query}"</strong> is generating high buyer inquiry volume. Ensure related stock is verified in the <strong>Inventory Management</strong> tab, feature matching models on the <strong>Storefront Homepage Banner</strong>, or configure a special WhatsApp flash sale discount in <strong>Offers &amp; Promotions</strong>.
                  </p>
                </div>
              </div>
            </div>
          )}
        </div>

        {/* Modal Bottom Action Bar */}
        <div className={`p-4 sm:px-6 border-t flex flex-wrap items-center justify-between gap-3 ${
          isDark ? 'border-slate-800 bg-slate-950/60' : 'border-slate-100 bg-slate-50'
        }`}>
          <div className="text-xs text-slate-400 flex items-center gap-1.5">
            <ShieldCheck className="w-4 h-4 text-emerald-500" />
            <span>2-Month Rolling Retention Engine • East Africa Time (EAT)</span>
          </div>

          <div className="flex items-center gap-2">
            <button
              type="button"
              onClick={onClose}
              className={`px-4 py-2 rounded-xl text-xs font-bold border transition-all cursor-pointer ${
                isDark 
                  ? 'bg-slate-800 hover:bg-slate-700 border-slate-700 text-white' 
                  : 'bg-white hover:bg-slate-100 border-slate-200 text-slate-800 shadow-xs'
              }`}
            >
              Close Inspector
            </button>
          </div>
        </div>
      </div>
    </div>
  );
};
